import { IdeaItem } from '../types/idea';

export function formatIdeaAsMarkdown(idea: IdeaItem): string {
  return `# ${idea.title}
*${idea.tagline}*

- **Primary Language:** ${idea.language}
- **Domain:** ${idea.domain}
- **Complexity:** ${idea.complexity}
- **Estimated Build Time:** ${idea.estimatedHours}
- **Tags:** ${idea.tags.join(', ')}

---

## 1. Problem Statement
${idea.problemStatement}

## 2. Core Architecture
${idea.coreArchitecture}

### Tech Stack
- **Primary Language:** ${idea.techStack.language}
${idea.techStack.framework ? `- **Framework:** ${idea.techStack.framework}\n` : ''}${idea.techStack.database ? `- **Database/Storage:** ${idea.techStack.database}\n` : ''}- **Protocols:** ${idea.techStack.protocols.join(', ')}
- **Key Libraries:** ${idea.techStack.libraries.join(', ')}

### Architecture Flow
${idea.architectureFlow.map((step, idx) => `${idx + 1}. ${step}`).join('\n')}

---

## 3. Key Technical Challenges & Edge Cases
${idea.keyChallenges
  .map(
    (c, idx) =>
      `### ${idx + 1}. ${c.title}
**Challenge:** ${c.description}  
**Mitigation Strategy:** ${c.solutionHint}
`
  )
  .join('\n')}

---

## 4. MVP Implementation Phases
${idea.mvpPhases
  .map(
    (p) => `### ${p.phase}: ${p.name} (${p.duration})
**Goals:**
${p.goals.map((g) => `- ${g}`).join('\n')}

**Deliverables:**
${p.deliverables.map((d) => `- ${d}`).join('\n')}
`
  )
  .join('\n')}

---

## 5. Learning Outcomes
${idea.learningOutcomes.map((l) => `- ${l}`).join('\n')}

## 6. Technical Interview Talking Points
${idea.interviewTalkingPoints.map((pt) => `- ${pt}`).join('\n')}

---
*Generated by IdeaFactory — Powered by Gemini 3.8 Flash*
`;
}

export function formatIdeaAsGitHubIssue(idea: IdeaItem): string {
  return `---
name: Feature / Project Spec: ${idea.title}
about: Full technical specification breakdown
title: "[SPEC] ${idea.title}"
labels: "${idea.language.toLowerCase()}, ${idea.domain.toLowerCase().replace(/[^a-z0-9]/g, '-')}, ${idea.complexity.toLowerCase().replace(/[^a-z0-9]/g, '-')}"
---

### Elevator Pitch
> ${idea.tagline}

### Context & Problem
${idea.problemStatement}

### Architectural Plan
${idea.coreArchitecture}

### Subsystems & Data Flow
${idea.architectureFlow.map((s) => `- [ ] ${s}`).join('\n')}

### MVP Checklist
${idea.mvpPhases
  .flatMap((phase) => [
    `#### ${phase.phase} - ${phase.name}`,
    ...phase.deliverables.map((d) => `- [ ] ${d}`),
  ])
  .join('\n')}

### Key Risks & Mitigations
${idea.keyChallenges.map((c) => `- **${c.title}**: ${c.solutionHint}`).join('\n')}
`;
}

export function downloadFile(filename: string, content: string, contentType = 'text/markdown') {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
